---
version: "2.0"

services:
  navi:
    image: registry.gitlab.com/fenil00/navi:v1.0
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
        http_options:
          max_body_size: 10485760  # 10MB
      - port: 50000
        as: 50000
        proto: udp
        to:
          - global: true
      - port: 50001
        as: 50001
        proto: udp
        to:
          - global: true
      - port: 50002
        as: 50002
        proto: udp
        to:
          - global: true
      - port: 50003
        as: 50003
        proto: udp
        to:
          - global: true
      - port: 50004
        as: 50004
        proto: udp
        to:
          - global: true
    env:
      # Core API Keys
      - AKASH_CHAT_API_KEY=
      - AKASH_CHAT_SMALL_MODEL=DeepSeek-R1-0528
      - AKASH_CHAT_LARGE_MODEL=Meta-Llama-3-2-3B-Instruct
      - AKASH_CHAT_BASE_URL=https://chatapi.akash.network/api/v1
      - OPENAI_BASE_URL=https://chatapi.akash.network/api/v1
      - OPENAI_API_KEY=
      - TAVILY_API_KEY=
      - DISCORD_APPLICATION_ID=
      - DISCORD_API_TOKEN=
      - DISCORD_INTENTS=Guilds,GuildMessages,MessageContent,GuildMembers
      - DISCORD_ALLOWED_DMS=true
      - DISCORD_ENABLE_WEB_SEARCH=true
      - CTX_KNOWLEDGE_ENABLED=false
      - LOAD_DOCS_ON_STARTUP=true
      - EMBEDDING_PROVIDER=akash
      - TEXT_EMBEDDING_MODEL=BAAI-bge-large-en-v1-5
      - EMBEDDING_DIMENSION=1024
      - MAX_CONCURRENT_REQUESTS=50
      - REQUESTS_PER_MINUTE=300
      - TOKENS_PER_MINUTE=200000
      - DOCS_REPO_1_URL=https://github.com/fenilmodi00/akash-knowledge-base.git
      - DOCS_REPO_1_PATH=./data/akash-knowledge-base
      - DOCS_REPO_1_BRANCH=main
      - NODE_ENV=production
      - LOG_LEVEL=debug
          
    # Health check configuration
    params:
      storage:
        data:
          mount: /app/data
          readOnly: false
        logs:
          mount: /app/logs
          readOnly: false

profiles:
  compute:
    navi:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gi
        storage:
          - size: 8Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3
          - name: logs
            size: 2Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    dcloud:
      pricing:
        navi:
          denom: uakt
          amount: 100000

deployment:
  navi:
    dcloud:
      profile: navi
      count: 1
