---
version: "2.0"

services:
  navi:
    image: registry.gitlab.com/fenil00/navi:v1.0
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
        http_options:
          max_body_size: 10485760  # 10MB
    env:
      # =============================================================================
      # API KEYS & AUTHENTICATION
      # =============================================================================
      - AKASH_CHAT_API_KEY=YOUR_AKASH_CHAT_API_KEY_HERE
      - OPENAI_API_KEY=YOUR_AKASH_CHAT_API_KEY_HERE
      - TAVILY_API_KEY=YOUR_TAVILY_API_KEY_HERE
      - DISCORD_APPLICATION_ID=YOUR_DISCORD_APPLICATION_ID_HERE
      - DISCORD_API_TOKEN=YOUR_DISCORD_BOT_TOKEN_HERE
      
      # =============================================================================
      # AKASH CHAT API CONFIGURATION
      # =============================================================================
      - AKASH_CHAT_BASE_URL=https://chatapi.akash.network/api/v1
      - OPENAI_BASE_URL=https://chatapi.akash.network/api/v1
      - AKASH_CHAT_SMALL_MODEL=Meta-Llama-3-2-3B-Instruct
      - AKASH_CHAT_LARGE_MODEL=DeepSeek-R1-0528
      - TEXT_PROVIDER=akash-chat
      - TEXT_MODEL=Meta-Llama-3-2-3B-Instruct
      
      # =============================================================================
      # EMBEDDING CONFIGURATION
      # =============================================================================
      - EMBEDDING_PROVIDER=akash-chat
      - AKASH_CHAT_EMBEDDING_MODEL=BAAI-bge-large-en-v1-5
      - AKASH_CHAT_EMBEDDING_DIMENSIONS=1024
      - TEXT_EMBEDDING_MODEL=BAAI-bge-large-en-v1-5
      - EMBEDDING_DIMENSION=1024
      
      # =============================================================================
      # PERFORMANCE & OPTIMIZATION (REDUCED FOR MINIMAL DEPLOYMENT)
      # =============================================================================
      - MAX_CONCURRENT_REQUESTS=50
      - REQUESTS_PER_MINUTE=300
      - TOKENS_PER_MINUTE=200000
      - RESPONSE_TIMEOUT=10000
      - MAX_RESPONSE_TIME=8000
      - AGENT_RESPONSE_TIMEOUT=8000
      - ENABLE_DOCUMENT_CACHING=true
      - CACHE_OPTIMIZATION=true
      
      # =============================================================================
      # DATABASE CONFIGURATION
      # =============================================================================
      - DATABASE_ENABLED=true
      - DISABLE_DATABASE=false
      - DATABASE_TIMEOUT=8000
      - VECTOR_SEARCH_ENABLED=true
      
      # =============================================================================
      # KNOWLEDGE BASE (OPTIMIZED FOR SPEED)
      # =============================================================================
      - CTX_KNOWLEDGE_ENABLED=false
      - LOAD_DOCS_ON_STARTUP=false
      
      # =============================================================================
      # DISCORD BOT BEHAVIOR
      # =============================================================================
      - DISCORD_INTENTS=Guilds,GuildMessages,MessageContent,GuildMembers
      - DISCORD_ALLOWED_DMS=true
      - DISCORD_ENABLE_WEB_SEARCH=true
      - DISCORD_SHOULD_RESPOND_ONLY_TO_MENTIONS=false
      - DISCORD_SHOULD_IGNORE_BOT_MESSAGES=true
      - DISCORD_SHOULD_IGNORE_DIRECT_MESSAGES=false
      - SHOULD_RESPOND_BYPASS_TYPES=dm,voice_dm,self,api,group
      - SHOULD_RESPOND_BYPASS_SOURCES=discord
      
      # =============================================================================
      # SYSTEM CONFIGURATION
      # =============================================================================
      - NODE_ENV=production
      - LOG_LEVEL=info
          
    # Minimal storage for basic operation
    params:
      storage:
        data:
          mount: /app/data
          readOnly: false

profiles:
  compute:
    navi:
      resources:
        cpu:
          units: 1  
        memory:
          size: 1Gi 
        storage:
          - size: 5Gi  
          - name: data
            size: 5Gi  
            attributes:
              persistent: true
              class: beta3
  placement:
    dcloud:
      pricing:
        navi:
          denom: uakt
          amount: 100000 
deployment:
  navi:
    dcloud:
      profile: navi
      count: 1
